version: '3.8'
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-client-rust-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "${PROMETHEUSE_PORT}:9090"
    depends_on:
      - redis-client-rust
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - redis-client-rust-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - redis-client-rust-network

  redis-client-rust:
    build:
      context: .
      dockerfile: Dockerfile
    image: redis-client-rust:v1.0
    container_name: redis-client-rust
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_POOL_CONNECTION=${REDIS_POOL_CONNECTION}
      - WORKERS=${WORKERS}
      - PLAYLOAD_LIMIT=${PLAYLOAD_LIMIT}
      - REQUEST_TIMEOUT_SEC=${REQUEST_TIMEOUT_SEC}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - redis
      - grafana
    networks:
      - redis-client-rust-network

networks:
  redis-client-rust-network:
    driver: bridge

volumes:
  redis-data:
  grafana_data:
