{
 "title": "Redis Client Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "label": "application", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "App Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "All RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(api_http_requests_total{instance=\"$instance\", job=\"$job\", status=~\"2..\"}[$__interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время ответа (99th pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, endpoint) (rate(api_app_http_request_duration_bucket{job=\"$job\", instance=\"$instance\"}[$__interval])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Errors RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(endpoint, status) (rate(api_http_requests_total{instance=\"$instance\", job=\"$job\", status!~\"2..\"}[$__interval]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время ответа (95th pct)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, endpoint) (rate(api_app_http_request_duration_bucket{job=\"$job\", instance=\"$instance\"}[$__interval])) > 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}